.PHONY: clean All

All:
	@echo "----------Building project:[ STL_topcoder - Debug ]----------"
	@cd "STL_topcoder" && "$(MAKE)" -f  "STL_topcoder.mk"
clean:
	@echo "----------Cleaning project:[ STL_topcoder - Debug ]----------"
	@cd "STL_topcoder" && "$(MAKE)" -f  "STL_topcoder.mk" clean
